### ISSUE TITLE
TODO notes left in docs

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [mad-lab-fau/tpcp#52]
re: openjournals/joss-reviews#4953

There are a handful of leftover `TODO` notes that appear in the rendered documentation. Some of these might be reasonable to leave in for now if they refer to not-yet-implemented features or examples (e.g., the 4th & 5th ones below?), but I think the first 3 are probably worth resolving in order to make the documentation complete.

- [ ] "TODO: add cites" under the "**Group 1**" subheading in the "[Categories of Algorithms](https://tpcp.readthedocs.io/en/latest/guides/algorithm_evaluation.html#categories-of-algorithms)" section of the [Algorithm Evaluation and Parameter Optimization](https://tpcp.readthedocs.io/en/latest/guides/algorithm_evaluation.html) page
- [ ] "TODO: Link" in the **Warning** in the docstring for [`tpcp.clone`](https://tpcp.readthedocs.io/en/latest/modules/generated/parameter/tpcp.clone.html#tpcp.clone)
- [ ] "learn more TODO" in the docstring for [`tpcp.PureParameter`](https://tpcp.readthedocs.io/en/latest/modules/generated/parameter/tpcp.PureParameter.html#tpcp.PureParameter)/[`tpcp.PurePara`](https://tpcp.readthedocs.io/en/latest/modules/generated/parameter/tpcp.PurePara.html#tpcp.PurePara)
  - (also, "`parameter`" and "`pure_paramter`" appear here in snake case&mdash;should these be camel case (i.e., "`Parameter`" and "`PureParamter`" to refer to the annotation classes?)
- [ ] "Todo: Full dedicated example for `PureParameter`" under the "[The Pipeline](https://tpcp.readthedocs.io/en/latest/auto_examples/parameter_optimization/_03_gridsearch_cv.html#the-pipeline)" heading in the [`GridSearchCV` example](https://tpcp.readthedocs.io/en/latest/auto_examples/parameter_optimization/_03_gridsearch_cv.html)
- [ ] "TODO: Make GridSearchCV aware of it!" near the end of the ["Optimization Info" example](https://tpcp.readthedocs.io/en/latest/auto_examples/other_features/_03_optimization_info.html)

**Comment by AKuederle** [comment]
Thanks again for your review!
I fully agree, many of these TODOs should be resolved.

I either resolved/implemented the changes (fd4e7f884d57d311a4714330b86a36c928b2040f) or turned the bigger once, that I might want to fix in the future into actual github issues and removed them as visibel todos form the code/docs (#56 #55)

I will close the issue. Feel free to reopen, in case you think further works should be done here.

**Comment by paxtonfitzpatrick** [comment]
Thanks @AKuederle! 

It looks like the third item in the list above ("learn more TODO", `parameter` vs `Parameter`, `pure_parameter` vs `PureParameter`) are still left in the docs. If you prefer to leave that page as-is for the moment because it's better/easier for you while developing, that's perfectly fine with me! I just want to make sure that wasn't accidental oversight, because I had assumed that TODO note was probably a placeholder for a link to https://tpcp.readthedocs.io/en/latest/guides/algorithm_evaluation.html#group-3-the-hybrid once that section of the docs had been finished.

Also, the 4th "Todo" in the list above (the one moved to #55) still appears in the updated version of the docs. Again, it's a tiny enough thing that I'm happy if you'd prefer to leave it in because it makes development easier&mdash;just want to make sure it was intentional because your comment seemed to indicate you meant to remove it.

Thanks again!

**Comment by AKuederle** [comment]
I honestly missed that one :) But I will leave it in for now and will but writing a proper example/guide for the PureParameter concept on my TODO list.
